# Generated by Django 3.2.16 on 2024-01-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone1', models.CharField(blank=True, max_length=100, null=True)),
                ('phone2', models.CharField(blank=True, max_length=100, null=True)),
                ('email1', models.EmailField(blank=True, max_length=100, null=True)),
                ('email2', models.EmailField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=1000, null=True)),
                ('facebook', models.CharField(blank=True, max_length=1000, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=1000, null=True)),
                ('telegram', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
