# Generated by Django 3.2.16 on 2024-02-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='envios',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='instagram',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='remesas',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
