# Generated by Django 3.2.16 on 2024-02-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_info', '0002_auto_20240210_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='whatsapp',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
