# Generated by Django 3.2.16 on 2024-02-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_info', '0003_alter_contactinfo_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='phone1',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone2',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='whatsapp',
            field=models.CharField(max_length=25),
        ),
    ]
