# Generated by Django 5.1.4 on 2025-02-18 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_info', '0004_auto_20240216_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='envios',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='remesas',
        ),
    ]
