# Generated by Django 5.1.4 on 2025-02-18 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_info', '0005_remove_contactinfo_envios_remove_contactinfo_remesas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactinfo',
            old_name='email1',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contactinfo',
            old_name='phone1',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='email2',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='phone2',
        ),
    ]
