# Generated by Django 5.1.4 on 2025-02-25 19:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_info', '0006_rename_email1_contactinfo_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='telegram',
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
