# Generated by Django 4.0.4 on 2022-11-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0011_video_delete_productvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='product_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
