# Generated by Django 4.0.4 on 2022-11-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0013_producto_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='product_img1',
            field=models.ImageField(blank=True, default='productos_images/blank.png', null=True, upload_to='productos_images'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='product_img2',
            field=models.ImageField(blank=True, default='productos_images/blank.png', null=True, upload_to='productos_images'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='product_img3',
            field=models.ImageField(blank=True, default='productos_images/blank.png', null=True, upload_to='productos_images'),
        ),
    ]
