# Generated by Django 3.2.16 on 2023-03-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0014_alter_categoria_nombre_alter_producto_product_img1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
    ]
