# Generated by Django 3.2.16 on 2023-04-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0018_auto_20230424_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
