# Generated by Django 3.2.16 on 2023-04-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0019_promotion_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='is_special',
            field=models.BooleanField(default=True),
        ),
    ]
