# Generated by Django 3.2.16 on 2023-04-30 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0021_auto_20230429_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad_puntuaciones',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='total_puntos',
        ),
    ]
