# Generated by Django 3.2.16 on 2023-04-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0022_auto_20230430_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad_puntuaciones',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='total_puntos',
            field=models.IntegerField(default=0),
        ),
    ]
