# Generated by Django 3.2.16 on 2023-05-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0025_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
