# Generated by Django 3.2.16 on 2023-05-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0028_producto_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='product_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
