# Generated by Django 3.2.16 on 2023-05-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0029_alter_producto_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='product_name',
            field=models.CharField(max_length=20),
        ),
    ]
