# Generated by Django 3.2.16 on 2023-06-03 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0031_producto_in_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
