# Generated by Django 3.2.16 on 2023-06-13 15:05

from django.db import migrations, models
import store_api.my_validators


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0032_delete_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={},
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(default=0, validators=[store_api.my_validators.validate_value_gte_cero]),
        ),
    ]
