# Generated by Django 3.2.16 on 2023-06-13 15:08

from django.db import migrations, models
import store_api.my_validators


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0033_auto_20230613_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad_puntuaciones',
            field=models.IntegerField(default=0, validators=[store_api.my_validators.validate_value_gte_cero]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descuento',
            field=models.FloatField(default=0, validators=[store_api.my_validators.validate_value_gte_cero]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='in_stock',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[store_api.my_validators.validate_value_gte_cero]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='puntuacion',
            field=models.IntegerField(default=0, validators=[store_api.my_validators.validate_value_gte_cero]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='total_puntos',
            field=models.IntegerField(default=0, validators=[store_api.my_validators.validate_value_gte_cero]),
        ),
    ]
