# Generated by Django 3.2.16 on 2023-12-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0034_auto_20230613_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
    ]
