# Generated by Django 3.2.16 on 2024-01-03 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0036_auto_20240103_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['-id']},
        ),
    ]
