# Generated by Django 3.2.16 on 2024-01-03 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0037_alter_score_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre', '-id']},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['-id']},
        ),
    ]
