# Generated by Django 3.2.16 on 2024-01-06 12:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0038_auto_20240103_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='promotion',
        ),
        migrations.AddField(
            model_name='promotion',
            name='description',
            field=models.CharField(default='Productos rebajados', max_length=200),
        ),
        migrations.AddField(
            model_name='promotion',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='img',
            field=models.ImageField(blank=True, default='productos_images/blank.png', null=True, upload_to='categories_images'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='is_special',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
