# Generated by Django 3.2.16 on 2024-01-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0040_auto_20240106_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='cant_products',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='discount_in_percent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='promotion',
            name='name',
            field=models.CharField(default='Promoción', max_length=200),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.CharField(default='Productos rebajados', max_length=500),
        ),
    ]
