# Generated by Django 3.2.16 on 2024-01-06 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0041_auto_20240106_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='cant_products',
        ),
    ]
