# Generated by Django 3.2.16 on 2024-01-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0042_remove_promotion_cant_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='cantidad_products',
            field=models.IntegerField(default=0),
        ),
    ]
