# Generated by Django 3.2.16 on 2024-01-06 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0043_promotion_cantidad_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='cantidad_products',
        ),
    ]
