# Generated by Django 3.2.16 on 2024-01-07 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0045_alter_producto_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['-id']},
        ),
    ]
