# Generated by Django 3.2.16 on 2024-01-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0046_alter_categoria_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='product_img1',
            field=models.ImageField(default='productos_images/blank.png', upload_to='productos_images'),
        ),
    ]
