# Generated by Django 3.2.16 on 2024-02-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0048_auto_20240123_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='discount_in_percent',
            field=models.FloatField(),
        ),
    ]
