# Generated by Django 3.2.16 on 2024-02-06 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0049_alter_promotion_discount_in_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='discount_in_percent',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=1)]),
        ),
    ]
