# Generated by Django 3.2.16 on 2024-02-06 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0050_alter_promotion_discount_in_percent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='user',
            new_name='created_by',
        ),
    ]
