# Generated by Django 3.2.16 on 2024-02-06 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0051_rename_user_producto_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='created_by',
        ),
    ]
