# Generated by Django 3.2.16 on 2024-02-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0054_auto_20240216_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='recommended',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
