# Generated by Django 3.2.16 on 2024-02-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0055_alter_producto_recommended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
    ]
