# Generated by Django 5.1.4 on 2025-01-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0056_auto_20240226_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='img',
            field=models.ImageField(default='productos_images/blank.png', upload_to='categories_images'),
        ),
    ]
