# Generated by Django 5.1.4 on 2025-01-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0058_alter_producto_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='product_description',
            field=models.CharField(blank=True, db_index=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='product_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.CharField(db_index=True, default='Productos rebajados', max_length=500),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='name',
            field=models.CharField(db_index=True, default='Promoción', max_length=200),
        ),
    ]
