# Generated by Django 5.1.4 on 2025-01-26 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0059_alter_categoria_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='keywords',
            field=models.TextField(blank=True, db_index=True, default=''),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(limit_value=0)]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='product_name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='puntuacion',
            field=models.IntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(limit_value=0)]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='recommended',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.CharField(default='Productos rebajados', max_length=500),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='is_special',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='name',
            field=models.CharField(db_index=True, default='Promoción', max_length=200, unique=True),
        ),
    ]
