# Generated by Django 5.1.4 on 2025-01-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0060_producto_keywords_alter_producto_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
