# Generated by Django 5.1.4 on 2025-02-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0061_alter_promotion_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
