# Generated by Django 5.1.4 on 2025-02-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0067_alter_categoria_img_alter_promotion_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='product_img1',
            field=models.ImageField(default='productos_images/blank.webp', max_length=255, upload_to='productos_images'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='product_img2',
            field=models.ImageField(blank=True, default='productos_images/blank.webp', max_length=255, null=True, upload_to='productos_images'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='product_img3',
            field=models.ImageField(blank=True, default='productos_images/blank.webp', max_length=255, null=True, upload_to='productos_images'),
        ),
    ]
