# Generated by Django 5.1.4 on 2025-02-21 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0068_alter_producto_product_img1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='discount_in_percent',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0)]),
        ),
    ]
