# Generated by Django 5.1.4 on 2026-01-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0069_alter_promotion_discount_in_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='product_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
