# Generated by Django 3.2.16 on 2023-06-04 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido_api', '0004_listapedido_finalizado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listapedido',
            old_name='id_pedido',
            new_name='pedido',
        ),
        migrations.RenameField(
            model_name='listapedido',
            old_name='id_producto',
            new_name='producto',
        ),
    ]
