# Generated by Django 3.2.16 on 2023-06-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteproductslist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
