# Generated by Django 3.2.16 on 2023-06-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_api', '0002_alter_favoriteproductslist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteproductslist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
