# Generated by Django 3.2.16 on 2024-02-06 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_seller',
        ),
    ]
